#!/usr/bin/env bash
# One-shot RunPod node bootstrap for Hetu-DiT cold-start tests.
# Run on the RunPod node as root (default RunPod ssh user).
#
# Steps:
#   1. Install K3s (single-node, no Traefik to avoid port conflicts).
#   2. Install nvidia-device-plugin DaemonSet so K3s sees GPUs as a
#      schedulable resource (`nvidia.com/gpu`).
#   3. Install KubeRay operator (RayCluster CRD + controller).
#   4. Pull SD3 model into /root/models (only if not already there).
#   5. Wait for hetudit:latest to be in K3s containerd (caller scp+ctr import).
#
# Idempotent: re-running is safe; each step skips if already done.

set -euo pipefail

# -- 1. K3s ----------------------------------------------------------------
if ! command -v k3s >/dev/null; then
    echo "[setup] installing K3s ..."
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -
    mkdir -p ~/.kube
    cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    chmod 600 ~/.kube/config
    export KUBECONFIG=~/.kube/config
fi
export KUBECONFIG=~/.kube/config
echo "[setup] K3s ready: $(kubectl get nodes -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}')"

# Sanity: K3s containerd should already have nvidia runtime preconfigured
# on RunPod base images; if not we'd need to drop /etc/rancher/k3s/config.toml.tmpl
ls /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl 2>/dev/null && cat - <<'EOF' || true
# K3s autogenerated containerd config — nvidia runtime detection runs at
# k3s install time. If K3s didn't pick up nvidia (no `nvidia` runtime in
# config.toml), drop a template at /etc/rancher/k3s/config.toml.tmpl with
# the nvidia plugin and `systemctl restart k3s`.
EOF

# -- 2. nvidia-device-plugin ----------------------------------------------
if ! kubectl -n kube-system get ds nvidia-device-plugin-daemonset >/dev/null 2>&1; then
    echo "[setup] installing nvidia-device-plugin ..."
    kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.5/nvidia-device-plugin.yml
fi
echo "[setup] nvidia-device-plugin: $(kubectl -n kube-system get ds nvidia-device-plugin-daemonset -o jsonpath='{.status.numberReady}/{.status.desiredNumberScheduled}' 2>/dev/null || echo pending)"

# Wait for nvidia.com/gpu to register on the node
for _ in $(seq 1 60); do
    GPUS=$(kubectl get nodes -o jsonpath='{.items[0].status.allocatable.nvidia\.com/gpu}' 2>/dev/null || echo 0)
    [[ "${GPUS}" -gt 0 ]] 2>/dev/null && break
    sleep 5
done
echo "[setup] node advertises ${GPUS:-0} GPUs"

# -- 3. KubeRay operator ---------------------------------------------------
if ! kubectl -n ray-system get deploy kuberay-operator >/dev/null 2>&1; then
    echo "[setup] installing KubeRay operator ..."
    kubectl create namespace ray-system 2>/dev/null || true
    kubectl apply --server-side -f https://github.com/ray-project/kuberay/releases/download/v1.1.1/kuberay-operator.yaml
fi
echo "[setup] KubeRay: $(kubectl -n ray-system get deploy kuberay-operator -o jsonpath='{.status.readyReplicas}/{.status.replicas}' 2>/dev/null || echo pending)"

# -- 4. SD3 model ---------------------------------------------------------
MODEL_DIR=/root/models/stable-diffusion-3-medium-diffusers
if [[ ! -f "${MODEL_DIR}/model_index.json" ]]; then
    echo "[setup] downloading SD3 model (huggingface) ..."
    pip install -q huggingface_hub 2>&1 | tail -1 || true
    HF_TOKEN_REQUIRED="To download SD3 you need a HuggingFace token with access to stabilityai/stable-diffusion-3-medium-diffusers."
    if [[ -z "${HF_TOKEN:-}" ]]; then
        echo "[setup] WARNING: HF_TOKEN not set. ${HF_TOKEN_REQUIRED}" >&2
        echo "[setup] set HF_TOKEN=hf_xxx and re-run, OR scp the model dir from PKU." >&2
    else
        python3 -c "
from huggingface_hub import snapshot_download
snapshot_download('stabilityai/stable-diffusion-3-medium-diffusers', local_dir='${MODEL_DIR}', token='${HF_TOKEN}')
"
    fi
fi

# -- 5. Image presence ----------------------------------------------------
if k3s ctr -n k8s.io images ls 2>/dev/null | grep -q hetudit:latest; then
    echo "[setup] hetudit:latest already imported"
else
    echo "[setup] hetudit:latest NOT in containerd. Run from caller machine:"
    echo "          scp /tmp/hetudit-app.tar root@<runpod-node>:/root/"
    echo "          ssh root@<runpod-node> 'k3s ctr -n k8s.io images import /root/hetudit-app.tar'"
fi

echo "[setup] DONE. kubectl ready: $(kubectl get nodes -o jsonpath='{.items[0].metadata.name}')"
